# Generated by Django 3.0.1 on 2020-01-12 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200112_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CourseDetail'),
        ),
    ]
