# Generated by Django 3.0.1 on 2020-01-12 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200112_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='courseChapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[{'初级', 1}, {'中级', 2}, {3, '高级'}], default=1, max_length=10),
        ),
    ]
