# Generated by Django 3.0.1 on 2020-01-12 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200112_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_detail',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.CourseDetail'),
            preserve_default=False,
        ),
    ]
