# Generated by Django 3.0.1 on 2020-01-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_course_course_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.IntegerField(choices=[{1, '初级'}, {2, '中级'}, {3, '高级'}], default=1),
        ),
    ]
