# Generated by Django 3.0.1 on 2020-01-12 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200112_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='courseChapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course', verbose_name='关联课程'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=128, verbose_name='章节名称'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.CourseDetail', verbose_name='课程详情'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.FileField(default='/static/course_img/default.png', upload_to='', verbose_name='课程图片'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.IntegerField(choices=[(1, '初级'), (2, '中级'), (3, '高级')], default=1, verbose_name='课程难度'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=32, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='recommend',
            field=models.ManyToManyField(to='api.Course', verbose_name='推荐课程'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='why',
            field=models.CharField(max_length=128, verbose_name='为什么学'),
        ),
    ]
