# Generated by Django 3.0.1 on 2020-01-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200112_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='recommend',
            field=models.ManyToManyField(related_name='rm', to='api.Course', verbose_name='推荐课程'),
        ),
    ]
