# Generated by Django 3.0.1 on 2020-01-15 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_token_userinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='UserToken',
        ),
    ]
