# Generated by Django 3.0.1 on 2020-01-29 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0014_article_articlesource_collection_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=99.99, max_digits=10, verbose_name='价格')),
                ('policy', models.SmallIntegerField(choices=[(1, '一个月'), (2, '3个月'), (3, '6个月'), (4, '8个月'), (5, '1年')], verbose_name='时间')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
