# Generated by Django 3.0.1 on 2020-01-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_pricepolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricepolicy',
            options={'verbose_name_plural': '价格策略'},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.CharField(default='/static/course_img/default.png', max_length=128, verbose_name='课程图片'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='price',
            field=models.CharField(default=99, max_length=64, verbose_name='价格'),
        ),
    ]
