# Generated by Django 3.0.1 on 2020-01-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_coupon_couponrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricepolicy',
            name='policy',
            field=models.SmallIntegerField(choices=[(30, '一个月'), (90, '3个月'), (180, '6个月'), (240, '8个月'), (365, '1年')], verbose_name='时间'),
        ),
    ]
